### PR TITLE
Shake for answer

### PR DESCRIPTION
**Pull request by amilcarsantos**
"Shake the phone" to trigger an answer..
Note: To run in emulator you need have installed the packages:
- qt5-qtdeclarative-import-sensors 
- qt5-qtsensors

### CODE REVIEW

**Comment by GoAlexander** [comment]
OK, thanks for contribution.  
I have a lot to do so I don`t know when I will make new release + bug with broadcom driver in my laptop and Sailfish SDK so I have to develop on Windows... :(  But I try to end new version as soon as possible!

**Comment by GoAlexander** [comment]
Hm... How to install QTsensors on Windows?  
I have some troubles... Can you explain how to deploy it?

**Comment by amilcarsantos** [comment]
I also use Windows do develop Sailfish App.
-- installing sensors in the emulator:
download the RPMs:
  http://repo.merproject.org/obs/mer-core:/i486:/devel/Core_i486/i486/

with putty.exe >  ssh the emulator (port 2223) 
seach for the missing packages
   ~ pkcon search name sensors  

Probably the versions won't match so, uninstall old versions:
~ pkcon remove qt5-sensors...
Probably from the emulator you wont be able to install throught the network so install from local:
~ pkcon install-local qt5-sensors...
~ pkcon install-local qt5-qtdeclarative-import-sensors...
Note: before uninstalling, backup your emulator .vdi file

You won't be able to emulator the sensors but this enables to run the App in the emulator.. 

link:
https://lists.sailfishos.org/pipermail/devel/2014-January/002792.html

**Comment by GoAlexander** [comment]
Good, I will try that. What about phone? Are these packages in OS?  
So, it needs only add `QT+=sensors`?

**Comment by amilcarsantos** [comment]
Yes, the phone has the sensors packages already installed.. You can check-it by running the command: pkcon search name sensors, in the 'terminal'.

And No, `QT+=..` is for C++, Qml loads things differently...

FYI: you should already be able to test the sensors by deploying in the app on the phone! The above steps are only for the emulator..

**Comment by GoAlexander** [comment]
Thanks for explanation!  
New version is in QA. What do you think maybe make shacking a bit more sensitive?  
But we will see feedback in harbour store about it...

**Comment by amilcarsantos** [comment]
Already in QA? I've sent the code mainly to help u towards the "ask 8-ball" similar app...

Do adjust the shake detection, I've only made some basic tests...

**Comment by amilcarsantos** [comment]
FYI: the % symbol is the math operator for the 'remaining of an integer division', thus (number % 20) will return a value between 0 and 19..

**Comment by GoAlexander** [comment]
> Already in QA? I've sent the code mainly to help u towards the "ask 8-ball" similar app... Do adjust the shake detection, I've only made some basic tests...

Oh, sorry. I thought that it was "finished code"... And I tested it. It worked overall good.  
But I understood  you.

> FYI: the % symbol is the math operator for the 'remaining of an integer division', thus (number % 20) will return a value between 0 and 19..

Shit... I knew it... Stupid mistake... Ok, will fix it in next update...  
Thanks for all tips!

**Comment by amilcarsantos** [comment]
> Shit... I knew it... Stupid mistake... Ok, will fix it in next update...

What do you mean with 'mistake'?? The array has 20 elements, thus the index goes from 0 to 19, the random division returns a value from 0 to 19.. It's look's OK..

**Comment by GoAlexander** [comment]
Hm... Yes, you are right! I understood wrong situation. In short forgotten ;) In general I know what is % and that arrays begin from [0]. ;)

**Pull request merged**
