### PR TITLE
New translations for german language

### PR DESCRIPTION
**Pull request by ladidadida**
Changed some of interpretations of meanings and also used "Du", as this is more and more common also in german language.

Open for comments!

### CODE REVIEW

**Comment by GoAlexander** [comment]
Wow! I like your translation seriously but `Hölchstwahrscheinlich` to `Höchstwahrscheinlich` and translations of `Outlook good` are different in Cover and in FirstPage in your in version. Please fix it and I will merge your branch :)  

P.S. I have to learn german more. :)))

**Comment by ladidadida** [comment]
Thanks for review. I will apply changes when I am back on my pc after weekend.

By the way: Nice software :)

**Comment by GoAlexander** [comment]
Ok :)

**Comment by GoAlexander** [comment]
Great! Thanks for your contribution!  
I will update the app soon.

**Pull request merged**
